# Generated by Django 2.2.7 on 2019-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=200)),
                ('task_is_done', models.BooleanField(default=False)),
                ('task_due_date', models.DateTimeField(verbose_name='date task')),
            ],
        ),
    ]
