# Generated by Django 2.2.7 on 2019-11-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_due_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_is_done',
            new_name='is_done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
    ]
